### ISSUE TITLE
Name the game...

### ISSUE THREAD

**Issue by HauHe** [HauHe/reeemgame#12]
The REEEM project ended several years ago, and in any case the project name does not indicate what the game is about. Hence, a name with a more catchy name would be good to have.
Instant ideas that come to my mind would be:

- PowerSystemPOV (PoSyPOV)
- Decide
- Make your POV count (MyPOV)
- The influence of decisions on the power system desgin (TIDO)
- Open Power System Design Game (OPSyGame)
- ...
Ok, some of these are random. But I'd be happy to hear what you think and what ideas or improvement suggestions you have for a catchy name.

**Comment by olavurellefsen** [comment]
I asked ChatGPT, and here are the suggestions:

**ÓE**: I am trying to find a catchy name for an educational game that we developed

**ChatGPT**: Sure! I'd be happy to help you come up with a catchy name for your educational game. Can you provide a bit more information about the game? What is its main focus or theme? Who is the target audience? Knowing these details can help me come up with a name that resonates with your users and reflects the essence of your game.

**ÓE**: The purpose of this game is to learn about energy systems. Participants learn how different decisions affect the energy systems and the outcomes for other stakeholders. The game has been created as part of the REEEM project and is based on OSeMBE, which is the open source energy model base for the European Union. The REEEM project is a EU funded project which aims to gain a better understanding of how energy strategies can help the transition to a low-carbon EU energy society.

**ChatGPT**: Based on the information you provided, here are a few possible name options for your educational game about energy systems:

- "PowerPlay" - This name implies a fun and engaging game that is related to energy and power systems.
- "Energy Quest" - This name suggests a journey or mission to discover and learn about energy systems, making it an attractive and exciting option for an educational game.
- "EcoCharge" - This name combines the concepts of energy and sustainability, which could be an ideal choice for an educational game that focuses on a low-carbon energy society.
- "Grid Genius" - This name evokes the idea of mastering a complex system or puzzle, which is fitting for a game that involves learning about energy systems and their components.
- "Watt's Up?" - This name is a playful take on the question "What's up?", while also referencing the unit of measurement for power. It could be a fun and catchy option for an educational game about energy systems.

I hope these options help inspire you to come up with a catchy name for your educational game about energy systems. Good luck!

**Comment by HauHe** [comment]
Nice! Thanks a lot @olavurellefsen! 
That indeed provides some inspiration :)

**Comment by FraGard** [comment]
PowerPlay is not bad. Maybe PowerPlay EU? Could sound slightly politically incorrect, but also ironic and engaging. 
@HauHe what does 'POV' stand for?

**Comment by HauHe** [comment]
I'm thinking of going "Power Decisions Game". What do you think any objections?

@FraGard, POV stands for "Point of View"

**Comment by olavurellefsen** [comment]
Good suggestion. "Power decision game" has not really been used before as far as I can see from DuckDuckGo and Google.

**Comment by HauHe** [comment]
Decided for: "Power Decisions Game"
